### ISSUE TITLE
correction 1 for src/core/base_libs/ESRGAN/models

### ISSUE THREAD

**Issue by Irenetwt** [1stDayHack/FDK#1]
1.  file needed to add :
src/core/base_libs/ESRGAN/models/RRDB_ESRGAN_x4.pth

file download link: 
Exception: Model weight not found! Please download it at **https://drive.google.com/file/d/1lq5UcxRWnZ5XUQzYD2lW2vFYBBFHdLff/view?usp=sharing**

// error code on demo1.ipynb

----> 3 super_res = SuperReser(name="SuperResssss")
      4 super_res

/content/FDK/src/core/super_res.py in __init__(self, name, device)
     23         #Set weights and check
     24         self.weight = 'src/core/base_libs/ESRGAN/models/RRDB_ESRGAN_x4.pth'
---> 25         if not os.path.isfile(self.weight): raise Exception("Model weight not found! Please download it at https://drive.google.com/file/d/1lq5UcxRWnZ5XUQzYD2lW2vFYBBFHdLff/view?usp=sharing")

**Comment by datacrisis** [comment]
Amended.
